# Generated by Django 6.0.3 on 2026-03-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('category', models.CharField(choices=[('GM', 'General Merit'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe'), ('OBC', 'Other Backward Class'), ('EWS', 'Economically Weaker Section'), ('CAT-1', 'Category 1'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B')], max_length=10)),
                ('entry_type', models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral')], max_length=10)),
                ('qualifying_exam', models.CharField(max_length=100)),
                ('qualifying_exam_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('document_status', models.CharField(choices=[('Pending', 'Pending'), ('Submitted', 'Submitted'), ('Verified', 'Verified')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_number', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('admission_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('fee_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='masters.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='masters.program')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='masters.quota')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
